In [1]:
!curl -O https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/101/397/original/Sachin_ODI.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26440  100 26440    0     0  15880      0  0:00:01  0:00:01 --:--:-- 15879

In [2]:
import pandas as pd
import numpy as np

sachin_odi = pd.read_csv("Sachin_ODI.csv")
sachin_odi.head()

,runs,NotOut,mins,bf,fours,sixes,sr,Inns,Opp,Ground,Date,Winner,Won,century
0,13,0,30,15,3,0,86.66,1,New Zealand,Napier,1995-02-16,New Zealand,False,False
1,37,0,75,51,3,1,72.54,2,South Africa,Hamilton,1995-02-18,South Africa,False,False
2,47,0,65,40,7,0,117.50,2,Australia,Dunedin,1995-02-22,India,True,False
3,48,0,37,30,9,1,160.00,2,Bangladesh,Sharjah,1995-04-05,India,True,False
4,4,0,13,9,1,0,44.44,2,Pakistan,Sharjah,1995-04-07,Pakistan,False,False

In [4]:
sachin_odi['runs'].describe()

count    360.000000
mean      43.241667
std       42.182452
min        0.000000
25%        8.000000
50%       30.000000
75%       67.000000
max      200.000000
Name: runs, dtype: float64

In [17]:
result= sachin_odi[(sachin_odi['runs']>=50) & (sachin_odi['Won']==True)]
result.head(5)

,runs,NotOut,mins,bf,fours,sixes,sr,Inns,Opp,Ground,Date,Winner,Won,century
5,112,1,137,107,15,1,104.67,2,Sri Lanka,Sharjah,1995-04-09,India,True,True
12,127,1,175,138,15,1,92.02,2,Kenya,Cuttack,1996-02-18,India,True,True
13,70,0,137,91,8,0,76.92,2,West Indies,Gwalior,1996-02-21,India,True,False
23,118,0,-,140,8,2,84.28,1,Pakistan,Sharjah,1996-04-15,India,True,True
30,89,1,-,89,9,3,100.00,2,Pakistan,Toronto,1996-09-16,India,True,False

In [18]:
event_a = sachin_odi[sachin_odi['runs'] >= 50]
event_b = sachin_odi[sachin_odi['Won'] == True]
event_c= pd.merge(event_a, event_b, how='inner')
event_c.head(5)

,runs,NotOut,mins,bf,fours,sixes,sr,Inns,Opp,Ground,Date,Winner,Won,century
0,112,1,137,107,15,1,104.67,2,Sri Lanka,Sharjah,1995-04-09,India,True,True
1,127,1,175,138,15,1,92.02,2,Kenya,Cuttack,1996-02-18,India,True,True
2,70,0,137,91,8,0,76.92,2,West Indies,Gwalior,1996-02-21,India,True,False
3,118,0,-,140,8,2,84.28,1,Pakistan,Sharjah,1996-04-15,India,True,True
4,89,1,-,89,9,3,100.00,2,Pakistan,Toronto,1996-09-16,India,True,False

In [23]:
sachin_odi[(sachin_odi['runs']>=50) | (sachin_odi['Won']==True)]

,runs,NotOut,mins,bf,fours,sixes,sr,Inns,Opp,Ground,Date,Winner,Won,century
2,47,0,65,40,7,0,117.50,2,Australia,Dunedin,1995-02-22,India,True,False
3,48,0,37,30,9,1,160.00,2,Bangladesh,Sharjah,1995-04-05,India,True,False
5,112,1,137,107,15,1,104.67,2,Sri Lanka,Sharjah,1995-04-09,India,True,True
6,41,0,51,41,5,0,100.00,2,Sri Lanka,Sharjah,1995-04-14,India,True,False
8,39,0,79,51,4,0,76.47,2,New Zealand,Amritsar,1995-11-18,India,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,48,0,87,63,5,0,76.19,2,Sri Lanka,Perth,2012-02-08,India,True,False
356,39,0,45,30,5,0,130.00,2,Sri Lanka,Hobart,2012-02-28,India,True,False
357,6,0,25,19,1,0,31.57,1,Sri Lanka,Dhaka,2012-03-13,India,True,False
358,114,0,205,147,12,1,77.55,1,Bangladesh,Dhaka,2012-03-16,Bangladesh,False,True
359,52,0,93,48,5,1,108.33,2,Pakistan,Dhaka,2012-03-18,India,True,False

In [24]:
pd.concat([event_a, event_b]).drop_duplicates()

,runs,NotOut,mins,bf,fours,sixes,sr,Inns,Opp,Ground,Date,Winner,Won,century
5,112,1,137,107,15,1,104.67,2,Sri Lanka,Sharjah,1995-04-09,India,True,True
10,65,0,96,59,9,1,110.16,2,New Zealand,Nagpur,1995-11-26,New Zealand,False,False
12,127,1,175,138,15,1,92.02,2,Kenya,Cuttack,1996-02-18,India,True,True
13,70,0,137,91,8,0,76.92,2,West Indies,Gwalior,1996-02-21,India,True,False
14,90,0,124,84,14,1,107.14,2,Australia,Mumbai,1996-02-27,Australia,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,2,0,4,4,0,0,50.00,1,West Indies,Chennai,2011-03-20,India,True,False
349,18,0,21,14,2,0,128.57,2,Sri Lanka,Mumbai,2011-04-02,India,True,False
351,48,0,87,63,5,0,76.19,2,Sri Lanka,Perth,2012-02-08,India,True,False
356,39,0,45,30,5,0,130.00,2,Sri Lanka,Hobart,2012-02-28,India,True,False
357,6,0,25,19,1,0,31.57,1,Sri Lanka,Dhaka,2012-03-13,India,True,False

In [16]:
import pandas as pd
sachin_odi = pd.read_csv("Sachin_ODI.csv")
event_compliment  = sachin_odi[~(sachin_odi['runs']>=50)]
event_compliment.head()

,runs,NotOut,mins,bf,fours,sixes,sr,Inns,Opp,Ground,Date,Winner,Won,century
0,13,0,30,15,3,0,86.66,1,New Zealand,Napier,1995-02-16,New Zealand,False,False
1,37,0,75,51,3,1,72.54,2,South Africa,Hamilton,1995-02-18,South Africa,False,False
2,47,0,65,40,7,0,117.50,2,Australia,Dunedin,1995-02-22,India,True,False
3,48,0,37,30,9,1,160.00,2,Bangladesh,Sharjah,1995-04-05,India,True,False
4,4,0,13,9,1,0,44.44,2,Pakistan,Sharjah,1995-04-07,Pakistan,False,False

In [13]:
exx = sachin_odi[ ~ sachin_odi.index.isin(sachin_odi[sachin_odi['runs'] >= 50].index) ]
exx

,runs,NotOut,mins,bf,fours,sixes,sr,Inns,Opp,Ground,Date,Winner,Won,century
0,13,0,30,15,3,0,86.66,1,New Zealand,Napier,1995-02-16,New Zealand,False,False
1,37,0,75,51,3,1,72.54,2,South Africa,Hamilton,1995-02-18,South Africa,False,False
2,47,0,65,40,7,0,117.50,2,Australia,Dunedin,1995-02-22,India,True,False
3,48,0,37,30,9,1,160.00,2,Bangladesh,Sharjah,1995-04-05,India,True,False
4,4,0,13,9,1,0,44.44,2,Pakistan,Sharjah,1995-04-07,Pakistan,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353,3,0,21,12,0,0,25.00,2,Australia,Brisbane,2012-02-19,Australia,False,False
354,22,0,33,23,3,0,95.65,2,Sri Lanka,Brisbane,2012-02-21,Sri Lanka,False,False
355,14,0,34,15,2,0,93.33,2,Australia,Sydney,2012-02-26,Australia,False,False
356,39,0,45,30,5,0,130.00,2,Sri Lanka,Hobart,2012-02-28,India,True,False
357,6,0,25,19,1,0,31.57,1,Sri Lanka,Dhaka,2012-03-13,India,True,False

In [21]:
#probability 
prob_a = len(event_a) / len(sachin_odi)

In [22]:
prob_a = len(event_a) / len(sachin_odi)
prob_b = len(event_b) / len(sachin_odi)

In [23]:
prob_a_and_b = len(sachin_odi[(sachin_odi['runs'] >= 50) & (sachin_odi['Won'] == 1)]) / len(sachin_odi)

In [24]:
p_aor_b = prob_a + prob_b - prob_a_and_b
p_aor_b

0.6388888888888888