In [153]:
import pandas as pd
import numpy as np

In [154]:
!gdown 16KtxSt_QEGQvfluEaMls5cCHPwhRXgCk
!gdown 19L3rYatfhbBL1r5MHrv-p_oM2wlvrhqk
!gdown 1OHLKJwA3qZopKPvlKoRldM6BvA1A4dYF
!gdown 1N7O_fWCTJLu8SIa_paKcDEzllgpMk8sK
!gdown 12Bh2AN8LcZAlg20ehpQrEWccUDaSdsOG

/Users/nithinys/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=16KtxSt_QEGQvfluEaMls5cCHPwhRXgCk
To: /Users/nithinys/GithubRepos/ml-ai-genai-ds-journal/module04-ML-coding:Suprivised-learing/ensemble_model/HR-Employee-Attrition.csv
100%|█████████████████████████████████████████| 228k/228k [00:00<00:00, 898kB/s]
/Users/nithinys/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=19L3rYatfhbBL1r5MHrv-p_oM2wlvrhqk
To: /Users/nithinys/GithubRepos/ml-ai-genai-ds-journal/module04-ML-coding:Suprivised-learing/ensemble_model/preprocessed_X_sm.pickle
100%|█████████████████████████████████████████| 534k/534k [00:01<00:00, 299kB/s]
/Users/nithinys/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1OHLKJwA3qZopKPvlKoRldM6BvA1A4dYF
To: /Users/nithinys/GithubRepos/ml-ai-genai-ds-journal/module04-ML-coding:Suprivised-learing/ensemble_model/X_test.pickle
100%|█████████████████████████████████████████| 111k/111k [00:00<00:00, 638kB/s]
/Users/nithinys/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1N7O_fWCTJLu8SIa_paKcDEzllgpMk8sK
To: /Users/nithinys/GithubRepos/ml-ai-genai-ds-journal/module04-ML-coding:Suprivised-learing/ensemble_model/y_sm.pickle
100%|██████████████████████████████████████| 15.4k/15.4k [00:00<00:00, 18.8MB/s]
/Users/nithinys/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=12Bh2AN8LcZAlg20ehpQrEWccUDaSdsOG
To: /Users/nithinys/GithubRepos/ml-ai-genai-ds-journal/module04-ML-coding:Suprivised-learing/ensemble_model/y_test.pickle
100%|██████████████████████████████████████| 9.49k/9.49k [00:00<00:00, 14.8MB/s]

In [155]:
pd.read_pickle("preprocessed_X_sm.pickle")

,Age,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,...,YearsWithCurrManager,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single
0,36,1174,3,4,0.233871,1,0,99,3,2,...,1,0.000000,0.000000,1.0,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000
1,21,546,5,1,0.127479,3,1,97,3,1,...,2,0.000000,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
2,43,422,1,3,0.151584,4,0,33,3,2,...,2,0.000000,1.000000,0.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000
3,42,188,29,3,0.127479,2,1,56,1,2,...,0,0.000000,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
4,35,992,1,3,0.127479,4,1,68,2,1,...,2,0.000000,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1843,41,1077,10,3,0.187471,2,1,85,2,2,...,4,0.407817,0.592183,0.0,0.000000,0.407817,0.592183,0.592183,0.000000,0.407817
1844,55,310,7,1,0.239573,3,1,71,3,1,...,7,0.000000,0.000000,1.0,0.000000,0.998141,0.001859,0.000000,0.998141,0.001859
1845,36,899,5,2,0.143813,1,0,92,2,1,...,2,0.677643,0.322357,0.0,0.000000,1.000000,0.000000,0.677643,0.322357,0.000000
1846,40,292,7,3,0.151584,1,1,84,3,3,...,5,0.192577,0.807423,0.0,0.000000,1.000000,0.000000,0.807423,0.192577,0.000000
1847,19,936,8,2,0.157015,3,0,85,2,1,...,0,0.000000,0.000000,1.0,0.263474,0.736526,0.000000,0.000000,0.000000,1.000000

In [156]:
import pandas as pd
import numpy as np

with open("preprocessed_X_sm.pickle", "rb") as handle:
    #X_train = pd.read_pickle(handle)
    X_train = pd.read_pickle("preprocessed_X_sm.pickle")

with open("X_test.pickle", "rb") as handle:
    X_test = pd.read_pickle(handle)
    
with open("y_sm.pickle", "rb") as handle:
    y_train = pd.read_pickle(handle)
    
with open("y_test.pickle", "rb") as handle:
    y_test = pd.read_pickle(handle)

In [157]:
X_train

,Age,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,...,YearsWithCurrManager,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single
0,36,1174,3,4,0.233871,1,0,99,3,2,...,1,0.000000,0.000000,1.0,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000
1,21,546,5,1,0.127479,3,1,97,3,1,...,2,0.000000,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
2,43,422,1,3,0.151584,4,0,33,3,2,...,2,0.000000,1.000000,0.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000
3,42,188,29,3,0.127479,2,1,56,1,2,...,0,0.000000,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
4,35,992,1,3,0.127479,4,1,68,2,1,...,2,0.000000,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1843,41,1077,10,3,0.187471,2,1,85,2,2,...,4,0.407817,0.592183,0.0,0.000000,0.407817,0.592183,0.592183,0.000000,0.407817
1844,55,310,7,1,0.239573,3,1,71,3,1,...,7,0.000000,0.000000,1.0,0.000000,0.998141,0.001859,0.000000,0.998141,0.001859
1845,36,899,5,2,0.143813,1,0,92,2,1,...,2,0.677643,0.322357,0.0,0.000000,1.000000,0.000000,0.677643,0.322357,0.000000
1846,40,292,7,3,0.151584,1,1,84,3,3,...,5,0.192577,0.807423,0.0,0.000000,1.000000,0.000000,0.807423,0.192577,0.000000
1847,19,936,8,2,0.157015,3,0,85,2,1,...,0,0.000000,0.000000,1.0,0.263474,0.736526,0.000000,0.000000,0.000000,1.000000

In [158]:
1848*0.2

369.6

In [159]:
X_test

,Age,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,...,YearsWithCurrManager,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single
681,38,1333,1,3,0.239583,4,0,80,3,3,...,11,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
946,40,299,25,4,0.233871,4,1,57,2,3,...,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
626,32,638,8,2,0.127479,3,0,91,4,2,...,3,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
1154,47,1176,26,4,0.151584,4,0,98,3,5,...,0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
669,39,1122,6,3,0.127479,4,1,70,3,1,...,2,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
952,31,1060,1,3,0.151584,4,0,54,3,1,...,2,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
165,50,1452,11,3,0.151584,3,0,53,3,5,...,4,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
270,55,452,1,3,0.127479,4,1,81,3,5,...,13,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
7,30,1358,24,1,0.151584,4,1,67,3,1,...,0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
1231,46,717,13,4,0.151584,3,1,34,3,2,...,9,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0

In [160]:
y_train

0       0
1       0
2       0
3       0
4       0
       ..
1843    1
1844    1
1845    1
1846    1
1847    1
Name: Attrition, Length: 1848, dtype: int64

In [161]:
from sklearn.tree import DecisionTreeClassifier

tree_clf = DecisionTreeClassifier(max_depth=4, random_state=7)
tree_clf.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=4, random_state=7)

In [162]:
print("train accuracy: {:2f}".format(tree_clf.score(X_train, y_train)*100))
print("test accuracy: {:2f}".format(tree_clf.score(X_test, y_test)*100))

train accuracy: 83.766234
test accuracy: 78.804348

In [163]:
X_train.shape

(1848, 36)

In [164]:
df = X_train.copy()
df['target'] = y_train.values

In [165]:
df.head()

,Age,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,...,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,target
0,36,1174,3,4,0.233871,1,0,99,3,2,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
1,21,546,5,1,0.127479,3,1,97,3,1,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0
2,43,422,1,3,0.151584,4,0,33,3,2,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0
3,42,188,29,3,0.127479,2,1,56,1,2,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0
4,35,992,1,3,0.127479,4,1,68,2,1,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0

In [166]:
df.shape[0]

1848

In [167]:
#function for row sampling

def sample_rows(df, percent):
    return df.sample(int(percent * df.shape[0]), replace=True)

In [168]:
sample_rows(df.head(), 0.9)

,Age,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,...,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,target
3,42,188,29,3,0.127479,2,1,56,1,2,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0
2,43,422,1,3,0.151584,4,0,33,3,2,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0
1,21,546,5,1,0.127479,3,1,97,3,1,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0
3,42,188,29,3,0.127479,2,1,56,1,2,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0

In [169]:
1848*0.2

369.6

In [170]:
df.columns.tolist()[:-1]

['Age',
 'DailyRate',
 'DistanceFromHome',
 'Education',
 'EducationField',
 'EnvironmentSatisfaction',
 'Gender',
 'HourlyRate',
 'JobInvolvement',
 'JobLevel',
 'JobRole',
 'JobSatisfaction',
 'MonthlyIncome',
 'MonthlyRate',
 'NumCompaniesWorked',
 'OverTime',
 'PercentSalaryHike',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'StockOptionLevel',
 'TotalWorkingYears',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager',
 'BusinessTravel_Non-Travel',
 'BusinessTravel_Travel_Frequently',
 'BusinessTravel_Travel_Rarely',
 'Department_Human Resources',
 'Department_Research & Development',
 'Department_Sales',
 'MaritalStatus_Divorced',
 'MaritalStatus_Married',
 'MaritalStatus_Single']

In [171]:
df.shape

(1848, 37)

In [172]:
import random
random.sample(df.columns.tolist()[:-1], int(0.5*(df.shape[1]-1)))

['Education',
 'MaritalStatus_Single',
 'DailyRate',
 'JobSatisfaction',
 'DistanceFromHome',
 'StockOptionLevel',
 'Age',
 'TrainingTimesLastYear',
 'MaritalStatus_Divorced',
 'EnvironmentSatisfaction',
 'JobRole',
 'YearsInCurrentRole',
 'RelationshipSatisfaction',
 'BusinessTravel_Travel_Rarely',
 'YearsWithCurrManager',
 'OverTime',
 'BusinessTravel_Non-Travel',
 'MaritalStatus_Married']

In [173]:
#function fetaure sampling

def sample_features(df, percent):
    cols= random.sample(df.columns.tolist()[:-1], int(percent*(df.shape[1]-1)))
    new_df = df[cols]
    new_df['target'] = df['target']
    return cols

In [174]:
sample_features(df, 0.2)

/var/folders/96/pzp77pgj2jngfzbn1nyzz6w80000gn/T/ipykernel_38873/1971325451.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['target'] = df['target']

['Department_Research & Development',
 'MonthlyIncome',
 'JobSatisfaction',
 'WorkLifeBalance',
 'HourlyRate',
 'MonthlyRate',
 'YearsWithCurrManager']

In [175]:
def combined_samples(df, row_percent, col_pecent):
    new_df = sample_rows(df, row_percent)
    return sample_features(new_df, col_pecent)

In [176]:
combined_samples(df, 0.5, 0.5)

/var/folders/96/pzp77pgj2jngfzbn1nyzz6w80000gn/T/ipykernel_38873/1971325451.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['target'] = df['target']

['StockOptionLevel',
 'MaritalStatus_Divorced',
 'JobInvolvement',
 'Department_Human Resources',
 'PercentSalaryHike',
 'BusinessTravel_Travel_Frequently',
 'TotalWorkingYears',
 'JobSatisfaction',
 'YearsAtCompany',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'Age',
 'Department_Sales',
 'Gender',
 'WorkLifeBalance',
 'BusinessTravel_Travel_Rarely',
 'JobLevel',
 'DistanceFromHome']

In [177]:
df1 = combined_samples(df, 0.5, 0.5)
df1

/var/folders/96/pzp77pgj2jngfzbn1nyzz6w80000gn/T/ipykernel_38873/1971325451.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['target'] = df['target']

['PercentSalaryHike',
 'JobRole',
 'EnvironmentSatisfaction',
 'DailyRate',
 'Department_Research & Development',
 'MonthlyRate',
 'JobLevel',
 'DistanceFromHome',
 'BusinessTravel_Non-Travel',
 'HourlyRate',
 'JobInvolvement',
 'Education',
 'MaritalStatus_Single',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'MaritalStatus_Married',
 'Department_Sales',
 'EducationField']

In [178]:
df2 = combined_samples(df, 0.5, 0.5)

/var/folders/96/pzp77pgj2jngfzbn1nyzz6w80000gn/T/ipykernel_38873/1971325451.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['target'] = df['target']

In [179]:
df3 = combined_samples(df, 0.5, 0.5)

/var/folders/96/pzp77pgj2jngfzbn1nyzz6w80000gn/T/ipykernel_38873/1971325451.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['target'] = df['target']

In [180]:
from sklearn.tree import DecisionTreeClassifier
clf1 = DecisionTreeClassifier()
clf2 = DecisionTreeClassifier()
clf3 = DecisionTreeClassifier()

In [182]:
clf1.fit(df1.iloc[:, :-1], df1.iloc[:, -1])
clf2.fit(df2.iloc[:, :-1], df2.iloc[:, -1])
clf3.fit(df3.iloc[:, :-1], df3.iloc[:, -1])

AttributeError: 'list' object has no attribute 'iloc'